export const GET_STATIONS = "GET_STATIONS";
export const GET_STATION_BY_ID = "GET_STATION_BY_ID";
export const UPDATE_STATION = "UPDATE_STATION";
export const DELETE_STATION = "DELETE_STATION";
export const CREATE_STATION = "CREATE_STATION";
